### PR TITLE
Added Transient Info Module

### PR DESCRIPTION
**Pull request by jpihl**
In my app I have certain debug infomation which is not relevant across the whole application, but only in some activities. I made this module which allows addition and removal of lines in the debug overlay.

What do you think - both about the idea, and my implementation?

### CODE REVIEW

**Comment by jpihl** [comment]
I just discovered that the picture referenced in the readme is missing. I was thinking of adding something like this:
TransientInfo

I don't know if the file is too large - it's 1.5 mb in this version.

**Comment by jpihl** [comment]
Hi @Manabu-GT,

I just wanted to make sure you've seen my PR :)

**Comment by Manabu-GT** [comment]
sorry for the delay. I've been sick for the last few days and had to take a couple of days off at my work. Once I catch up with my work items first, I will take a look at this PR and get back to you within the next few days.

Anyway, thanks for your contribution!

Manabu

**Comment by jpihl** [comment]
No problem at all, take all the time you need :)

**Comment by Manabu-GT** [comment]
@jpihl 

Sorry for the delay. 
I'm wondering how useful this was during your development. 
Did you also happen to use the LogcatModule which could potentially provide similar behaviors?

Thanks!

**Comment by jpihl** [comment]
Hi @Manabu-GT,

No problem, I've kept myself busy with other stuff in the meantime.

My motivation behind this module is to use it for a video player. Having this module would give me an efficient way to show stuff like dropped frames, number of frames buffered, etc.

I think I can accomplish the same thing with multiple filtered `LogcatModule`s. However this approach has two down sides:
1. Depending on how often I log the values, I will drown all other `logcat` messages (if I'm not using a filter)
2. Unless I clutter my code with debug guards I will perform the calculations regardless of whether the debug overlay is turned on or not.

**Comment by jpihl** [comment]
Hi @Manabu-GT,

Did you have time to read my motivation?
I can also make this into a separate repository if you do not feel that it should be a part of DebugOverlay-Android.

**Comment by Manabu-GT** [comment]
@jpihl 

Sorry for my late response. I gave it some thoughts, but I currently prefer having your TransientModule in a separate repository (your repository) and just have a link to your repo on the README if that's ok with you. 

Please let me know once you push this code into your repo so that I can update the README to include a link to it.

Thanks!

**Comment by jpihl** [comment]
No problem, thanks for taking the time to look at it. I'll make it a separate repository. I don't have any experience with the deployment to Maven central, so I may need your help with that..

**Comment by jpihl** [comment]
Hi again @Manabu-GT,

I figured out how to deploy it to maven central. Here's a link to the finished repository with the extension:
https://github.com/jpihl/DebugOverlay-Android-TransientInfo

I tried following the style of this repository as much as possible - I hope you don't mind.

**Comment by jpihl** [comment]
Oh, and BTW - while looking through your code, to figure out how to do the maven deployment, I discovered these faulty links:
https://github.com/Manabu-GT/DebugOverlay-Android/blob/master/gradle.properties#L36-L37
I think they are missing your username.

**Comment by Manabu-GT** [comment]
@jpihl Oh, Thanks for pointing out that it's missing my username. Will update :)

**Pull request closed without merging**
