### PR TITLE
Remove interval from BaseDataModule

### PR DESCRIPTION
**Pull request by jpihl**
Hi Manabu-GT,

First of all I really like your library. I did however find it a bit odd that the `BaseDataModule` contained the 
refresh `interval` since not all `BaseDataModule`s need it, e.g., the `IPAddressDataModule`, and potentially other custom modules. This PR addresses this "issue". I'm putting issue in quotes since I don't know if you feel the same way.
Anyway I dont want to come off as ungrateful, the library is awesome, I just wanted to help make it even better.

### CODE REVIEW

**Comment by Manabu-GT** [comment]
@jpihl Thanks for your PR. I originally added an interval variable in a base class because the first modules I wrote all required it. Since the number of modules increased and the capability of adding a custom module exists today, I now agree that it's better to remove an interval from the base class. 

I will merge your PR and release the new version along with other minor changes as v1.1.2.

Thank you for using this library!

**Comment by jpihl** [comment]
Thanks for merging!

Would you be interested in having more modules in the library or do want to keep the number low so that you don't have to make no-op versions of them? I have a network stats module that I would be more than happy to contribute.

**Comment by Manabu-GT** [comment]
@jpihl 

I certainly welcome contributions, but I'm currently reluctant to add any more modules in the core library. Instead, I'm currently working on adding extra overlays as a separate module. You can get an idea of what I mean at https://github.com/Manabu-GT/DebugOverlay-Android/tree/develop/debugoverlay-ext-timber. Once that work gets complete, I will let you know so that you can follow the same pattern and contribute your network stats module as an extension within this repo.

Thanks!

**Comment by jpihl** [comment]
I think I understand the idea, let me just be sure:
You want the extension modules to be in separated into different android modules and then deploy them   
separately to maven central?

So if i wanted to use the library with the timber module I would have to include the following in my `build.gradle` file:
    
    ...
    // core library
    debugCompile 'com.ms-square:debugoverlay:x.x.x'
    releaseCompile 'com.ms-square:debugoverlay-no-op:x.x.x'
    testCompile 'com.ms-square:debugoverlay-no-op:x.x.x'

    // extra modules
    debugCompile 'com.ms-square:debugoverlay-ext-timber:x.x.x'
    ...

Having the debug modules in separate android modules adds some nice flexibility. If you move all the modules to separate modules I bet you could lower the total number of method/field references in the core library. If you want any help with that, let me know.

**Comment by Manabu-GT** [comment]
> You want the extension modules to be in separated into different android modules and then deploy them
separately to maven central?

Yes. 

So, I expect to see something like below in the build.gradle.
```groovy
dependencies {
  debugCompile 'com.ms-square:debugoverlay:1.1.2'
  releaseCompile 'com.ms-square:debugoverlay-no-op:1.1.2'
  testCompile 'com.ms-square:debugoverlay-no-op:1.1.2'
  
  compile ('com.ms-square:debugoverlay-ext-timber:1.1.2') {
    exclude module: 'debugoverlay'
  }
}
```

or

```groovy
dependencies {
  // this will use a full debugoverlay lib even in the test/release build
  compile 'com.ms-square:debugoverlay-ext-timber:1.1.2'
}
```

>  If you move all the modules to separate modules I bet you could lower the total number of method/field references in the core library. 

Yeah, but I will probably keep the existing modules in the core library as it is unless I get at least a couple of requests from multiple developers since the number of total methods in a no-op version should not really matter in most cases.

**Comment by Manabu-GT** [comment]
just released a Timber extension in v1.1.2.
https://github.com/Manabu-GT/DebugOverlay-Android/tree/master/debugoverlay-ext-timber

You can create a new directory such as "debugoverlay-ext-networkstats" and send me a PR for contribution. I will be looking forward to seeing the module you have built.

Thanks for your help!

Manabu

**Pull request merged**
